### ISSUE TITLE
`#version` is hidden from GLSL in Rust string literals

### ISSUE THREAD

**Issue by marc0246** [vulkano-rs/vulkano-book#8]
In Rust code blocks, [mdBook hides lines starting with `#`](https://rust-lang.github.io/mdBook/format/mdbook.html#hiding-code-lines), which causes the string literals used by vulkano-shaders in Rust code blocks to not render the `#version 460` line. This is of course not the desired outcome. This supposedly works the same as in rustdoc, so I'm assuming using double hashtag `##` will escape the symbol.

**Comment by Nekomansa** [comment]
`##` does escape the the symbol! I'll have a pull request with the fix soon.
