### ISSUE TITLE
Outdated note on `impl_vertex!`

### ISSUE THREAD

**Issue by marc0246** [vulkano-rs/vulkano-book#9]
Another thing that was overlooked when updating the guide is this outdated note:
https://github.com/vulkano-rs/vulkano-book/blob/c22c1594d3e611617163d134eb2a7a6bf4694803/src/graphics_pipeline/vertex_shader.md?plain=1#L105-L106
This should now say something about the `Vertex` derive macro.

**Comment by Nekomansa** [comment]
Oh, I was wondering what this was referring to. I need to read up on how the derive macro works, but I can try writing a new note once I have an understanding.
